#21 env 구조 변경
sparcs-kaist/taxiSampleGenerator pull request #22
Opened 2022-11-16 13:14 UTC by chlehdwon

it closes #21

2022-11-16 13:48 UTC, withSang requested changes
오 감사합니다!!

2022-11-16 13:48 UTC, withSang commented on index.js
> +  const numberOfChats = 200;
생각해보니까 `numberOfRooms`와 `numberOfChats`는 사용자가 바꿀 일이 종종 있을 것 같습니다!
예를 들어 서비스를 배포하기 위해 DB에 장소만 추가하고 싶은 경우에요.
이 변수들만 `.env`에 다시 분리하는 것 어떨까요?

예를 들어 `security.js`가 아래와 같이 작동할 수 있어요!
```javascript
module.exports = {
  loadSampleData,
  mongo: process.env.DB_PATH,
  numberOfRooms: parseInt(process.env.NUM_OF_ROOMS) || 2,
  numberOfChats: parseInt(process.env.NUM_OF_CHATS) || 200,
};
```

2022-11-16 13:49 UTC, withSang commented on index.js
> +  const numberOfChats = 200;
`parseInt(undefined) === NaN`이라 문제없을 것 같아요!

2022-11-16 13:53 UTC, withSang commented on index.js
> +  const numberOfChats = 200;
"채팅 메시지 빈도"와 같은 다른 환경변수들도 같은 방법으로 기본값을 설정할 수 있어요!

2022-11-16 14:11 UTC, chlehdwon commented on index.js
> +  const numberOfChats = 200;
아 그런 방법이 있군요! 좋은 것 같아요!!!

2022-11-22 13:57 UTC, withSang approved these changes
수고하셨습니다!!

2022-11-22 13:59 UTC, merged